
import { Translation, Language } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  vi: {
    title: 'DMP AI Landing & Website Builder',
    subtitle: 'Tạo Landing Page hoặc Website chuyên nghiệp chỉ từ một prompt duy nhất. Tối ưu SEO & Sẵn sàng triển khai.',
    promptPlaceholder: 'Ví dụ: Landing page cho dịch vụ thiết kế nội thất cao cấp, phong cách tối giản, màu kem chủ đạo...',
    generateBtn: 'Bắt đầu khởi tạo Website',
    landingLabel: 'Landing Page (Đơn trang)',
    websiteLabel: 'Website (Đa trang)',
    selectPages: 'Chọn các trang cần tạo:',
    about: 'Giới thiệu',
    services: 'Dịch vụ',
    products: 'Sản phẩm',
    blog: 'Tin tức',
    contact: 'Liên hệ',
    portfolio: 'Dự án (Portfolio)',
    pricing: 'Bảng giá',
    testimonials: 'Đánh giá (Testimonials)',
    faq: 'Hỏi đáp (FAQ)',
    team: 'Đội ngũ',
    terminal_analyzing: 'Đang phân tích yêu cầu người dùng...',
    terminal_detecting: 'Xác định cấu trúc website...',
    terminal_content: 'Đang sinh nội dung bằng AI...',
    terminal_design: 'Thiết kế giao diện Modern UI/UX...',
    terminal_seo: 'Tối ưu SEO & Schema.org...',
    terminal_exporting: 'Đóng gói mã nguồn hoàn chỉnh...',
    preview: 'Xem trước',
    code: 'Mã nguồn',
    deploy: 'Triển khai',
    download: 'Tải về',
    donate: 'Ủng hộ',
    guide: 'Hướng dẫn',
    features: 'Tính năng',
    adminLabel: 'Kèm trang quản trị (Admin Dashboard)',
    referenceUrlLabel: 'Link Website Mẫu (Để AI học phong cách)',
    referenceUrlPlaceholder: 'Dán link website bạn muốn AI tham khảo màu sắc, bố cục (ví dụ: https://apple.com)...',
    referenceImageLabel: 'Tải lên ảnh mẫu (AI phân tích giao diện)',
    referenceImagePlaceholder: 'Click để tải ảnh hoặc kéo thả vào đây...',
    removeImage: 'Xóa ảnh'
  },
  en: {
    title: 'DMP AI Landing & Website Builder',
    subtitle: 'Create a professional Landing Page or Website from a single prompt. SEO optimized & Deployment-ready.',
    promptPlaceholder: 'Example: Landing page for high-end interior design service, minimal style, cream dominant colors...',
    generateBtn: 'Start Generating Website',
    landingLabel: 'Landing Page (Single)',
    websiteLabel: 'Website (Multi-page)',
    selectPages: 'Select pages to generate:',
    about: 'About Us',
    services: 'Services',
    products: 'Products',
    blog: 'Blog',
    contact: 'Contact',
    portfolio: 'Portfolio',
    pricing: 'Pricing',
    testimonials: 'Testimonials',
    faq: 'FAQ',
    team: 'Team',
    terminal_analyzing: 'Analyzing user requirements...',
    terminal_detecting: 'Detecting website structure...',
    terminal_content: 'Generating content with AI...',
    terminal_design: 'Designing Modern UI/UX...',
    terminal_seo: 'Optimizing SEO & Schema.org...',
    terminal_exporting: 'Exporting complete source code...',
    preview: 'Preview',
    code: 'Source Code',
    deploy: 'Deploy',
    download: 'Download',
    donate: 'Donate',
    guide: 'Guide',
    features: 'Features',
    adminLabel: 'Include Admin Dashboard',
    referenceUrlLabel: 'Reference Website URL (For Style Learning)',
    referenceUrlPlaceholder: 'Paste a website link for AI to reference style & layout (e.g., https://apple.com)...',
    referenceImageLabel: 'Upload Reference Image (AI UI Analysis)',
    referenceImagePlaceholder: 'Click to upload or drag & drop image here...',
    removeImage: 'Remove Image'
  }
};

export const PAGE_OPTIONS = [
  { id: 'about', labelKey: 'about' as keyof Translation },
  { id: 'services', labelKey: 'services' as keyof Translation },
  { id: 'products', labelKey: 'products' as keyof Translation },
  { id: 'blog', labelKey: 'blog' as keyof Translation },
  { id: 'contact', labelKey: 'contact' as keyof Translation },
  { id: 'portfolio', labelKey: 'portfolio' as keyof Translation },
  { id: 'pricing', labelKey: 'pricing' as keyof Translation },
  { id: 'testimonials', labelKey: 'testimonials' as keyof Translation },
  { id: 'faq', labelKey: 'faq' as keyof Translation },
  { id: 'team', labelKey: 'team' as keyof Translation }
];
