
import { Translation, Language } from './types';

export const TRANSLATIONS: Record<Language, Translation> = {
  vi: {
    title: 'DMP AI Landing & Website Builder',
    subtitle: 'Tạo Landing Page hoặc Website chuyên nghiệp chỉ từ một prompt duy nhất. Tối ưu SEO & Sẵn sàng triển khai.',
    promptPlaceholder: 'Ví dụ: Landing page cho dịch vụ thiết kế nội thất cao cấp, phong cách tối giản, màu kem chủ đạo...',
    generateBtn: 'Bắt đầu khởi tạo Website',
    landingLabel: 'Landing Page (Đơn trang)',
    websiteLabel: 'Website (Đa trang)',
    selectPages: 'Chọn các trang cần tạo:',
    selectOptions: 'Chọn các tính năng bổ sung:',
    // Pages
    about: 'Giới thiệu',
    services: 'Dịch vụ',
    products: 'Sản phẩm',
    blog: 'Tin tức',
    contact: 'Liên hệ',
    portfolio: 'Dự án (Portfolio)',
    pricing: 'Bảng giá',
    testimonials: 'Đánh giá (Testimonials)',
    faq: 'Hỏi đáp (FAQ)',
    team: 'Đội ngũ',
    // New Pages
    booking: 'Đặt lịch hẹn',
    gallery: 'Thư viện ảnh',
    caseStudies: 'Case Studies',
    careers: 'Tuyển dụng',
    privacy: 'Chính sách & Điều khoản',
    resources: 'Tài liệu/Downloads',
    courses: 'Khóa học',
    // Options
    chatbot: 'Chatbot AI Agent',
    newsletter: 'Đăng ký Newsletter',
    partners: 'Logo đối tác/Clients',
    map: 'Bản đồ Google Maps',
    videoHero: 'Video Hero',
    stats: 'Số liệu thống kê',
    awards: 'Chứng chỉ/Giải thưởng',
    promoPopup: 'Popup khuyến mãi',
    appDownload: 'Tải ứng dụng (App CTA)',
    liveChat: 'Live Chat Widget',
    multiLang: 'Hỗ trợ đa ngôn ngữ',
    rating: 'Đánh giá sao',
    // Terminal
    terminal_analyzing: 'Đang phân tích yêu cầu người dùng...',
    terminal_detecting: 'Xác định cấu trúc website...',
    terminal_content: 'Đang sinh nội dung bằng AI...',
    terminal_design: 'Thiết kế giao diện Modern UI/UX...',
    terminal_seo: 'Tối ưu SEO & Schema.org...',
    terminal_exporting: 'Đóng gói mã nguồn hoàn chỉnh...',
    preview: 'Xem trước',
    code: 'Mã nguồn',
    deploy: 'Triển khai',
    download: 'Tải về',
    donate: 'Ủng hộ',
    guide: 'Hướng dẫn',
    features: 'Tính năng',
    adminLabel: 'Kèm trang quản trị (Admin Dashboard)',
    referenceUrlLabel: 'Link Website Mẫu (Để AI học phong cách)',
    referenceUrlPlaceholder: 'Dán link website bạn muốn AI tham khảo màu sắc, bố cục (ví dụ: https://apple.com)...',
    referenceImageLabel: 'Tải lên ảnh mẫu (AI phân tích giao diện)',
    referenceImagePlaceholder: 'Click để tải ảnh hoặc kéo thả vào đây...',
    removeImage: 'Xóa ảnh'
  },
  en: {
    title: 'DMP AI Landing & Website Builder',
    subtitle: 'Create a professional Landing Page or Website from a single prompt. SEO optimized & Deployment-ready.',
    promptPlaceholder: 'Example: Landing page for high-end interior design service, minimal style, cream dominant colors...',
    generateBtn: 'Start Generating Website',
    landingLabel: 'Landing Page (Single)',
    websiteLabel: 'Website (Multi-page)',
    selectPages: 'Select pages to generate:',
    selectOptions: 'Select additional features:',
    // Pages
    about: 'About Us',
    services: 'Services',
    products: 'Products',
    blog: 'Blog',
    contact: 'Contact',
    portfolio: 'Portfolio',
    pricing: 'Pricing',
    testimonials: 'Testimonials',
    faq: 'FAQ',
    team: 'Team',
    // New Pages
    booking: 'Booking/Appointments',
    gallery: 'Photo Gallery',
    caseStudies: 'Case Studies',
    careers: 'Careers',
    privacy: 'Privacy & Terms',
    resources: 'Resources/Downloads',
    courses: 'Courses',
    // Options
    chatbot: 'AI Chatbot Agent',
    newsletter: 'Newsletter Signup',
    partners: 'Partner/Client Logos',
    map: 'Google Maps',
    videoHero: 'Video Hero',
    stats: 'Stats Counter',
    awards: 'Certifications/Awards',
    promoPopup: 'Promo Popup',
    appDownload: 'App Download CTA',
    liveChat: 'Live Chat Widget',
    multiLang: 'Multi-language Support',
    rating: 'Star Rating',
    // Terminal
    terminal_analyzing: 'Analyzing user requirements...',
    terminal_detecting: 'Detecting website structure...',
    terminal_content: 'Generating content with AI...',
    terminal_design: 'Designing Modern UI/UX...',
    terminal_seo: 'Optimizing SEO & Schema.org...',
    terminal_exporting: 'Exporting complete source code...',
    preview: 'Preview',
    code: 'Source Code',
    deploy: 'Deploy',
    download: 'Download',
    donate: 'Donate',
    guide: 'Guide',
    features: 'Features',
    adminLabel: 'Include Admin Dashboard',
    referenceUrlLabel: 'Reference Website URL (For Style Learning)',
    referenceUrlPlaceholder: 'Paste a website link for AI to reference style & layout (e.g., https://apple.com)...',
    referenceImageLabel: 'Upload Reference Image (AI UI Analysis)',
    referenceImagePlaceholder: 'Click to upload or drag & drop image here...',
    removeImage: 'Remove Image'
  }
};

// Original 10 pages + 7 new pages = 17 page options
export const PAGE_OPTIONS = [
  // Original pages
  { id: 'about', labelKey: 'about' as keyof Translation },
  { id: 'services', labelKey: 'services' as keyof Translation },
  { id: 'products', labelKey: 'products' as keyof Translation },
  { id: 'blog', labelKey: 'blog' as keyof Translation },
  { id: 'contact', labelKey: 'contact' as keyof Translation },
  { id: 'portfolio', labelKey: 'portfolio' as keyof Translation },
  { id: 'pricing', labelKey: 'pricing' as keyof Translation },
  { id: 'testimonials', labelKey: 'testimonials' as keyof Translation },
  { id: 'faq', labelKey: 'faq' as keyof Translation },
  { id: 'team', labelKey: 'team' as keyof Translation },
  // New pages
  { id: 'booking', labelKey: 'booking' as keyof Translation },
  { id: 'gallery', labelKey: 'gallery' as keyof Translation },
  { id: 'caseStudies', labelKey: 'caseStudies' as keyof Translation },
  { id: 'careers', labelKey: 'careers' as keyof Translation },
  { id: 'privacy', labelKey: 'privacy' as keyof Translation },
  { id: 'resources', labelKey: 'resources' as keyof Translation },
  { id: 'courses', labelKey: 'courses' as keyof Translation }
];

// 12 component/widget options
export const COMPONENT_OPTIONS = [
  { id: 'chatbot', labelKey: 'chatbot' as keyof Translation, icon: '🤖' },
  { id: 'newsletter', labelKey: 'newsletter' as keyof Translation, icon: '📰' },
  { id: 'partners', labelKey: 'partners' as keyof Translation, icon: '🤝' },
  { id: 'map', labelKey: 'map' as keyof Translation, icon: '📍' },
  { id: 'videoHero', labelKey: 'videoHero' as keyof Translation, icon: '🎬' },
  { id: 'stats', labelKey: 'stats' as keyof Translation, icon: '📊' },
  { id: 'awards', labelKey: 'awards' as keyof Translation, icon: '🏆' },
  { id: 'promoPopup', labelKey: 'promoPopup' as keyof Translation, icon: '🎉' },
  { id: 'appDownload', labelKey: 'appDownload' as keyof Translation, icon: '📱' },
  { id: 'liveChat', labelKey: 'liveChat' as keyof Translation, icon: '💬' },
  { id: 'multiLang', labelKey: 'multiLang' as keyof Translation, icon: '🌐' },
  { id: 'rating', labelKey: 'rating' as keyof Translation, icon: '⭐' }
];
